#================================== Description ========================================
# Filebeat Config to send Elasticsearch/Logstash/Kibana in a docker host to Elasticsea-
# sh cluster.
filebeat.inputs:
- type: log
  paths:
    - /my-logs/log
  fields_under_root: true

#================================ Autodiscover =======================================
# Autodiscover all containers with elasticsearch images, and add an separate input for
# each container and log type.

# Output to Logstash
output.logstash:
  hosts: ["${LOGSTASH_HOST_PORT}"]

# Change index

# output.elasticsearch.index: "${LOCAL_HOSTNAME}-logs"
# setup.template.name: "${LOCAL_HOSTNAME}-logs"
# setup.template.pattern: "${LOCAL_HOSTNAME}-logs"

#=================================== Kibana ==========================================
# Enable setting up Kibana
# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup:
  kibana:
    host: 'https://${KIBANA_HOST_PORT}'
    username: '${ELASTIC_USERNAME}'
    password: '${ELASTIC_PASSWORD}'
  ssl:
    enabled: true
    verification_mode: none

setup.dashboards:
  enabled: true
  # index: "${LOCAL_HOSTNAME}-logs"

# Defines if the HTTP endpoint is enabled.
http.enabled: true
http.host: 0.0.0.0
http.port: 5066