filebeat.modules:
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true
- module: auditd
  log:
    enabled: true

# --------------------------- Filebeat autodiscover ------------------------

filebeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
      # This URL alos contains instructions on multi-line logs
      hints.enabled: true

# --------------------------- Filebeat inputs -----------------------------

filebeat.inputs:
- type: log
  paths:
    - /custom-app/log
  fields:
    event.dataset: my-app 
    # fields_under_root: true

# ---------------------------- Processors ---------------------------------

processors:
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

# ----------------------------- Change index -------------------------------

output.elasticsearch.index: "filebeat-%{[agent.version]}"
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-%{[agent.version]}"

# --------------------------- Output to Logstash ----------------------------

output.logstash:
  hosts: ["${LOGSTASH_HOST_PORT}"]

# ----------------------------- Kibana ------------------------------------

setup:
  kibana:
    host: '${KIBANA_HOST_PORT}'
    username: '${ELASTIC_USERNAME}'
    password: '${ELASTIC_PASSWORD}'
    ssl:
      enabled: true
      verification_mode: none

# ---------------------------- Dashboards --------------------------------

setup.dashboards:
  enabled: true
  index: "filebeat-*"

# ---------------------------= Xpack Monitoring ---------------------------

xpack.monitoring:
  enabled: true
  elasticsearch:

# Defines if the HTTP endpoint is enabled.
http.enabled: true
http.host: 0.0.0.0
http.port: 5066