version: '3.5'

volumes:
  filebeat-data:

services:
  # Docker Logs Shipper ------------------------------
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    hostname: "${HOSTNAME}-filebeat"
    restart: always
    user: root
    volumes:
      - ./filebeat/filebeat.logs.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # system and audit logs
      - /var/log/:/var/log/:ro
      - /var/log/audit/:/var/log/audit/:ro
      # custom logs and filebeat data
      - /home/oleh/study/elk:/custom-app/log
      - filebeat-data:/var/lib/filebeat/data
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_HOST_PORT: https://${KIBANA_HOST_PUB}:${KIBANA_PORT_PUB}
      LOGSTASH_HOST_PORT: ${LOGSTASH_HOST_PUB}:${LOGSTASH_PORT_PUB}
      ELASTICSEARCH_HOST_PORT: https://${ELASTICSEARCH_HOST_PUB}:${ELASTICSEARCH_PORT_PUB}
    # disable strict permission checks: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
    command: -e --strict.perms=false