# https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml

metricbeat.modules:
#------------------------------- System Module -------------------------------
- module: system
  metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime

#================================ Processors ===================================
processors:
# - add_cloud_metadata: ~
# - add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Elasticsearch output ===============================
output:
  elasticsearch:
    hosts: ["${ELASTICSEARCH_HOST_PORT}"]
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    ssl:
      enabled: true
      verification_mode: none

#============================== Dashboards =====================================
# setup.dashboards:
#   enabled: true
#   # index: "${LOCAL_HOSTNAME}-logs"

#============================== Kibana =========================================
setup:
  kibana:
    host: "${KIBANA_HOST_PORT}"
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    ssl:
      enabled: true
      verification_mode: none

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch: